Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/GuardClause:
  Exclude:
    - './*.gemspec'

Metrics/BlockLength:
  Exclude:
    - './*.gemspec'

Metrics/LineLength:
  Exclude:
    - './*.gemspec'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'lib/chronopost_fuel_adjustment_coefficients.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/chronopost_fuel_adjustment_coefficients.rb'
    - 'test/chronopost_fuel_adjustment_coefficients_test.rb'
