---
sudo: false

language: ruby

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.3
  - 2.6.0-preview3

os:
  - linux
  - osx

cache:
  bundler: true

before_install:
  - gem install bundler -v 1.17.1

script:
  - bundle install
  - bundle exec rake test
